#-------------------------------
# General Site Settings
title: Flower-dev
# logo: logo.svg # You can add own logo.
description: Blog


#-------------------------------
# Author Settings
author:
  name: Flower-dev
  image: 01.png
  say-hello: Hello, moi c'est <strong>Flower</strong>
  bio: Je suis une jeune développeuse Front-End souhaitant vous partager mes recherches et ma veille technique. Je vous souhaite une très bonne lecture !


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle
github: https://github.com/ # Add your Github handle
linkedin: https://www.linkedin.com/ # Add your Linkedin handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
